name: build-mingw
on: push
jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: prepare
      shell: cmd
      run: |
        call pull-mysql
        call pull-postgresql
        call pull-clang-mingw
        call pull-mingw
        move /y C:\mingw64 C:\mingw64_
        move /y "C:\Program Files\PostgreSQL" "C:\Program Files\PostgreSQL_"
        move /y "C:\Program Files\MySQL" "C:\Program Files\MySQL_"
        move /y "C:\Program Files\OpenSSL" "C:\Program Files\OpenSSL_"
        move /y C:\Strawberry C:\Strawberry_
        move /y C:\tools\php C:\tools\php_
        move /y "C:\Program Files\LLVM" "C:\Program Files\LLVM_"
    - name: configure
      shell: cmd
      run: |
        set PATH=C:\mysql-8.2.0-winx64\bin;C:\mysql-8.2.0-winx64\lib;C:\postgresql-14\bin;C:\Qt\6.8.1\mingw_64\bin;%LOCALAPPDATA%\Programs\Python\Python313;%LOCALAPPDATA%\Programs\Python\Python313\Scripts;C:\Python313;C:\Python313\Scripts;C:\Miniconda;C:\Miniconda\Scripts;C:\Program Files\CMake\bin;C:\llvm19\bin;C:\mingw1310_64\bin;C:\Program Files\7-Zip;%PATH%
        where mugideploy > NUL 2>&1 || pip install mugideploy
        where ninja > NUL 2>&1 || pip install ninja
        set LLVM_INSTALL_DIR=C:\llvm19
        if not exist qt-everywhere-src-6.8.1.zip (
            echo downloading qt-everywhere-src-6.8.1.zip
            curl -L -o qt-everywhere-src-6.8.1.zip https://qt.mirror.constant.com/official_releases/qt/6.8/6.8.1/single/qt-everywhere-src-6.8.1.zip
        )
        if not exist qt-everywhere-src-6.8.1 7z x -y qt-everywhere-src-6.8.1.zip
        pushd qt-everywhere-src-6.8.1
            if not exist build mkdir build
            pushd build
                cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DQT_BUILD_SUBMODULES="qtbase;qtsvg;qtactiveqt;qtserialport;qtimageformats;qtshadertools;qtdeclarative;qttools;qtdoc" -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=C:\Qt\6.8.1\mingw_64 -DQT_QMAKE_TARGET_MKSPEC=win32-g++ -DQT_BUILD_TESTS=FALSE -DQT_BUILD_EXAMPLES=FALSE -DFEATURE_system_zlib=OFF -DFEATURE_sql_mysql=ON -DFEATURE_sql_psql=ON -DPostgreSQL_ROOT=C:/postgresql-14 -DMySQL_ROOT=C:/mysql-8.2.0-winx64 -Wno-dev ..
            popd
        popd
    - name: qtbase
      shell: cmd
      run: |
        set PATH=C:\mysql-8.2.0-winx64\bin;C:\mysql-8.2.0-winx64\lib;C:\postgresql-14\bin;C:\Qt\6.8.1\mingw_64\bin;%LOCALAPPDATA%\Programs\Python\Python313;%LOCALAPPDATA%\Programs\Python\Python313\Scripts;C:\Python313;C:\Python313\Scripts;C:\Miniconda;C:\Miniconda\Scripts;C:\Program Files\CMake\bin;C:\llvm19\bin;C:\mingw1310_64\bin;%PATH%
        where mugideploy > NUL 2>&1 || pip install mugideploy
        where ninja > NUL 2>&1 || pip install ninja
        set LLVM_INSTALL_DIR=C:\llvm19
        pushd qt-everywhere-src-6.8.1\build
            ninja qtbase
            ninja qtbase/install
            mugideploy copy-dep --bin C:\Qt\6.8.1\mingw_64\bin\qmake.exe --dst C:\Qt\6.8.1\mingw_64\bin
            mugideploy copy-dep --bin C:\mysql-8.2.0-winx64\lib\libmysql.dll --dst C:\Qt\6.8.1\mingw_64\bin
            mugideploy copy-dep --bin C:\postgresql-14\lib\libpq.dll --dst C:\Qt\6.8.1\mingw_64\bin
        popd
    - name: qtsvg
      shell: cmd
      run: |
        set PATH=C:\mysql-8.2.0-winx64\bin;C:\mysql-8.2.0-winx64\lib;C:\postgresql-14\bin;C:\Qt\6.8.1\mingw_64\bin;%LOCALAPPDATA%\Programs\Python\Python313;%LOCALAPPDATA%\Programs\Python\Python313\Scripts;C:\Python313;C:\Python313\Scripts;C:\Miniconda;C:\Miniconda\Scripts;C:\Program Files\CMake\bin;C:\llvm19\bin;C:\mingw1310_64\bin;%PATH%
        where mugideploy > NUL 2>&1 || pip install mugideploy
        where ninja > NUL 2>&1 || pip install ninja
        set LLVM_INSTALL_DIR=C:\llvm19
        pushd qt-everywhere-src-6.8.1\build
            ninja qtsvg
            ninja qtsvg/install
        popd
    - name: qtactiveqt
      shell: cmd
      run: |
        set PATH=C:\mysql-8.2.0-winx64\bin;C:\mysql-8.2.0-winx64\lib;C:\postgresql-14\bin;C:\Qt\6.8.1\mingw_64\bin;%LOCALAPPDATA%\Programs\Python\Python313;%LOCALAPPDATA%\Programs\Python\Python313\Scripts;C:\Python313;C:\Python313\Scripts;C:\Miniconda;C:\Miniconda\Scripts;C:\Program Files\CMake\bin;C:\llvm19\bin;C:\mingw1310_64\bin;%PATH%
        where mugideploy > NUL 2>&1 || pip install mugideploy
        where ninja > NUL 2>&1 || pip install ninja
        set LLVM_INSTALL_DIR=C:\llvm19
        pushd qt-everywhere-src-6.8.1\build
            ninja qtactiveqt
            ninja qtactiveqt/install
        popd
    - name: qtserialport
      shell: cmd
      run: |
        set PATH=C:\mysql-8.2.0-winx64\bin;C:\mysql-8.2.0-winx64\lib;C:\postgresql-14\bin;C:\Qt\6.8.1\mingw_64\bin;%LOCALAPPDATA%\Programs\Python\Python313;%LOCALAPPDATA%\Programs\Python\Python313\Scripts;C:\Python313;C:\Python313\Scripts;C:\Miniconda;C:\Miniconda\Scripts;C:\Program Files\CMake\bin;C:\llvm19\bin;C:\mingw1310_64\bin;%PATH%
        where mugideploy > NUL 2>&1 || pip install mugideploy
        where ninja > NUL 2>&1 || pip install ninja
        set LLVM_INSTALL_DIR=C:\llvm19
        pushd qt-everywhere-src-6.8.1\build
            ninja qtserialport
            ninja qtserialport/install
        popd
    - name: qtimageformats
      shell: cmd
      run: |
        set PATH=C:\mysql-8.2.0-winx64\bin;C:\mysql-8.2.0-winx64\lib;C:\postgresql-14\bin;C:\Qt\6.8.1\mingw_64\bin;%LOCALAPPDATA%\Programs\Python\Python313;%LOCALAPPDATA%\Programs\Python\Python313\Scripts;C:\Python313;C:\Python313\Scripts;C:\Miniconda;C:\Miniconda\Scripts;C:\Program Files\CMake\bin;C:\llvm19\bin;C:\mingw1310_64\bin;%PATH%
        where mugideploy > NUL 2>&1 || pip install mugideploy
        where ninja > NUL 2>&1 || pip install ninja
        set LLVM_INSTALL_DIR=C:\llvm19
        pushd qt-everywhere-src-6.8.1\build
            ninja qtimageformats
            ninja qtimageformats/install
        popd
    - name: qtshadertools
      shell: cmd
      run: |
        set PATH=C:\mysql-8.2.0-winx64\bin;C:\mysql-8.2.0-winx64\lib;C:\postgresql-14\bin;C:\Qt\6.8.1\mingw_64\bin;%LOCALAPPDATA%\Programs\Python\Python313;%LOCALAPPDATA%\Programs\Python\Python313\Scripts;C:\Python313;C:\Python313\Scripts;C:\Miniconda;C:\Miniconda\Scripts;C:\Program Files\CMake\bin;C:\llvm19\bin;C:\mingw1310_64\bin;%PATH%
        where mugideploy > NUL 2>&1 || pip install mugideploy
        where ninja > NUL 2>&1 || pip install ninja
        set LLVM_INSTALL_DIR=C:\llvm19
        pushd qt-everywhere-src-6.8.1\build
            ninja qtshadertools
            ninja qtshadertools/install
        popd
    - name: qtdeclarative
      shell: cmd
      run: |
        set PATH=C:\mysql-8.2.0-winx64\bin;C:\mysql-8.2.0-winx64\lib;C:\postgresql-14\bin;C:\Qt\6.8.1\mingw_64\bin;%LOCALAPPDATA%\Programs\Python\Python313;%LOCALAPPDATA%\Programs\Python\Python313\Scripts;C:\Python313;C:\Python313\Scripts;C:\Miniconda;C:\Miniconda\Scripts;C:\Program Files\CMake\bin;C:\llvm19\bin;C:\mingw1310_64\bin;%PATH%
        where mugideploy > NUL 2>&1 || pip install mugideploy
        where ninja > NUL 2>&1 || pip install ninja
        set LLVM_INSTALL_DIR=C:\llvm19
        pushd qt-everywhere-src-6.8.1\build
            ninja qtdeclarative
            ninja qtdeclarative/install
        popd
    - name: qttools
      shell: cmd
      run: |
        set PATH=C:\mysql-8.2.0-winx64\bin;C:\mysql-8.2.0-winx64\lib;C:\postgresql-14\bin;C:\Qt\6.8.1\mingw_64\bin;%LOCALAPPDATA%\Programs\Python\Python313;%LOCALAPPDATA%\Programs\Python\Python313\Scripts;C:\Python313;C:\Python313\Scripts;C:\Miniconda;C:\Miniconda\Scripts;C:\Program Files\CMake\bin;C:\llvm19\bin;C:\mingw1310_64\bin;%PATH%
        where mugideploy > NUL 2>&1 || pip install mugideploy
        where ninja > NUL 2>&1 || pip install ninja
        set LLVM_INSTALL_DIR=C:\llvm19
        pushd qt-everywhere-src-6.8.1\build
            ninja qttools
            ninja qttools/install
            mugideploy copy-dep --bin C:\Qt\6.8.1\mingw_64\bin\qdoc.exe --dst C:\Qt\6.8.1\mingw_64\bin
        popd
    - name: qtdoc
      shell: cmd
      run: |
        set PATH=C:\mysql-8.2.0-winx64\bin;C:\mysql-8.2.0-winx64\lib;C:\postgresql-14\bin;C:\Qt\6.8.1\mingw_64\bin;%LOCALAPPDATA%\Programs\Python\Python313;%LOCALAPPDATA%\Programs\Python\Python313\Scripts;C:\Python313;C:\Python313\Scripts;C:\Miniconda;C:\Miniconda\Scripts;C:\Program Files\CMake\bin;C:\llvm19\bin;C:\mingw1310_64\bin;%PATH%
        where mugideploy > NUL 2>&1 || pip install mugideploy
        where ninja > NUL 2>&1 || pip install ninja
        set LLVM_INSTALL_DIR=C:\llvm19
        pushd qt-everywhere-src-6.8.1\build
            ninja qtdoc
            ninja qtdoc/install
        popd
    - name: docs
      shell: cmd
      run: |
        set PATH=C:\mysql-8.2.0-winx64\bin;C:\mysql-8.2.0-winx64\lib;C:\postgresql-14\bin;C:\Qt\6.8.1\mingw_64\bin;%LOCALAPPDATA%\Programs\Python\Python313;%LOCALAPPDATA%\Programs\Python\Python313\Scripts;C:\Python313;C:\Python313\Scripts;C:\Miniconda;C:\Miniconda\Scripts;C:\Program Files\CMake\bin;C:\llvm19\bin;C:\mingw1310_64\bin;%PATH%
        where mugideploy > NUL 2>&1 || pip install mugideploy
        where ninja > NUL 2>&1 || pip install ninja
        set LLVM_INSTALL_DIR=C:\llvm19
        pushd qt-everywhere-src-6.8.1\build
            ninja docs
            ninja install_docs
        popd
    - name: qwt
      shell: cmd
      run: |
        set PATH=C:\mysql-8.2.0-winx64\bin;C:\mysql-8.2.0-winx64\lib;C:\postgresql-14\bin;C:\Qt\6.8.1\mingw_64\bin;%LOCALAPPDATA%\Programs\Python\Python313;%LOCALAPPDATA%\Programs\Python\Python313\Scripts;C:\Python313;C:\Python313\Scripts;C:\Miniconda;C:\Miniconda\Scripts;C:\Program Files\CMake\bin;C:\llvm19\bin;C:\mingw1310_64\bin;C:\Program Files\Git\cmd;%PATH%
        where mugideploy > NUL 2>&1 || pip install mugideploy
        where ninja > NUL 2>&1 || pip install ninja
        set LLVM_INSTALL_DIR=C:\llvm19
        if not exist qwt (
            git clone https://git.code.sf.net/p/qwt/git qwt
            pushd qwt
                git checkout v6.3.0
            popd
        )
        pushd qwt
            "C:\Program Files\Git\usr\bin\patch.exe" -N -p1 -i ../0001-release-no-examples-no-tests-install-prefix.patch
            qmake
            mingw32-make -j4
            mingw32-make install
        popd
    - name: main
      shell: cmd
      run: |
        set PATH=C:\Program Files\7-Zip;%PATH%
        7z a -y Qt-6.8.1-mingw.zip C:\Qt\6.8.1\mingw_64
        7z a -y Qwt-6.3.0-Qt-6.8.1-mingw.zip C:\Qwt-6.3.0-Qt-6.8.1
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: Qt-6.8.1-mingw
        path: C:\Qt\6.8.1\mingw_64
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: Qwt-6.3.0-Qt-6.8.1-mingw
        path: C:\Qwt-6.3.0-Qt-6.8.1
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: mugideploy.log
        path: qt-everywhere-src-6.8.1\build\mugideploy.log
