name: main
on: push
jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: cleanup
      shell: cmd
      run: |
        move /y C:\mingw64 C:\mingw64_
        move /y "C:\Program Files\PostgreSQL" "C:\Program Files\PostgreSQL_"
        move /y "C:\Program Files\MySQL" "C:\Program Files\MySQL_"
        move /y "C:\Program Files\OpenSSL" "C:\Program Files\OpenSSL_"
        move /y C:\Strawberry C:\Strawberry_
        move /y C:\tools\php C:\tools\php_
    - name: pull
      shell: cmd
      run: |
        call pull-mingw
        call pull-mysql
        call pull-postgresql
    - name: build
      shell: cmd
      run: |
        set PATH=C:\mingw1310_64\bin;C:\Miniconda;C:\Miniconda\Scripts;C:\Windows;C:\Windows\System32
        call qt681
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: Qt-6.8.1
        path: C:/Qt/6.8.1/mingw_64
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: Qwt-6.3.0-Qt-6.8.1
        path: C:/Qwt-6.3.0-Qt-6.8.1
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: mugideploy
        path: mugideploy.log
    - name: release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          Qt-6.8.1.zip
          Qwt-6.3.0-Qt-6.8.1.zip
          mugideploy.log
